// Lab2_PAI/home-pantry/src/components/ProductCard.jsx
import { useCallback } from 'react';
import { Card, Badge, Button } from 'react-bootstrap';
import { useNavigate } from 'react-router-dom';
import { usePantry } from '../context/PantryContext';

function getExpiryStatus(expiry) {
  const today = new Date();
  const expiryDate = new Date(expiry);
  const diffDays = Math.ceil((expiryDate - today) / (1000 * 60 * 60 * 24));

  if (diffDays < 0) return { variant: 'danger', label: 'Przeterminowany' };
  if (diffDays <= 3) return { variant: 'warning', label: `Kończy się (${diffDays}d)` };
  return { variant: 'success', label: `OK (${diffDays}d)` };
}

export default function ProductCard({ product }) {
  const { removeProduct } = usePantry();
  const navigate = useNavigate();
  const status = getExpiryStatus(product.expiry);

  const handleRemove = useCallback(() => {
    removeProduct(product.id);
  }, [product.id, removeProduct]);

  return (
    <Card className="h-100 shadow-sm">
      <Card.Header className="bg-success text-white d-flex justify-content-between align-items-center">
        <strong>{product.name}</strong>
        <Badge bg={status.variant} text={status.variant === 'warning' ? 'dark' : undefined}>
          {status.label}
        </Badge>
      </Card.Header>
      <Card.Body>
        <p className="mb-1"><small className="text-muted">Kategoria:</small> {product.category}</p>
        <p className="mb-1"><small className="text-muted">Ilość:</small> {product.amount} {product.unit}</p>
        <p className="mb-1"><small className="text-muted">Ważność:</small> {product.expiry}</p>
        {product.opened && <Badge bg="info" text="dark">Otwarty</Badge>}
        {product.notes && <p className="mt-2 mb-0 text-muted"><small>{product.notes}</small></p>}
      </Card.Body>
      <Card.Footer className="d-flex gap-2">
        <Button
          variant="outline-success"
          size="sm"
          className="flex-grow-1"
          onClick={() => navigate(`/product/${product.id}`)}
        >
          Szczegóły
        </Button>
        <Button variant="outline-danger" size="sm" onClick={handleRemove}>
          🗑️
        </Button>
      </Card.Footer>
    </Card>
  );
}

// Lab3_PAI/spizarnia/src/app/shared/components/product-card/product-card.component.ts
import { Component, input, computed, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { Product, getExpiryStatus, EXPIRY_BADGE } from '../../../core/models/product.model';
import { PantryService } from '../../../core/services/pantry.service';

@Component({
  selector: 'app-product-card',
  standalone: true,
  imports: [RouterLink],
  template: `
    <div class="card h-100 shadow-sm">
      <div class="card-header bg-success text-white d-flex justify-content-between align-items-center">
        <strong>{{ product().name }}</strong>
        <span class="badge bg-{{ badge().bg }} {{ badge().bg === 'warning' ? 'text-dark' : '' }}">
          {{ badge().text }}
        </span>
      </div>
      <div class="card-body">
        <p class="mb-1">
          <small class="text-muted">Kategoria:</small> {{ product().category }}
        </p>
        <p class="mb-1">
          <small class="text-muted">Ilość:</small>
          {{ product().amount }} {{ product().unit }}
        </p>
        <p class="mb-1">
          <small class="text-muted">Ważność:</small> {{ product().expiry }}
        </p>
        @if (product().opened) {
          <span class="badge bg-info text-dark">Otwarty</span>
        }
        @if (product().notes) {
          <p class="mt-2 mb-0 text-muted">
            <small>{{ product().notes }}</small>
          </p>
        }
      </div>
      <div class="card-footer d-flex gap-2">
        <a [routerLink]="['/product', product().id]"
           class="btn btn-outline-success btn-sm flex-grow-1">
          Szczegóły
        </a>
        <button class="btn btn-outline-danger btn-sm"
                (click)="pantry.removeProduct(product().id)">
          🗑️
        </button>
      </div>
    </div>
  `,
})
export class ProductCardComponent {
  product = input.required<Product>();
  pantry = inject(PantryService);
  badge = computed(() => EXPIRY_BADGE[getExpiryStatus(this.product().expiry)]);
}
